name: 'CI Test Flask App'
description: 'Run tests for Flask application in app/hello-fincra'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  working-directory:
    description: 'Working directory for the Flask app'
    required: false
    default: 'app/hello-fincra'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    
    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        pytest --verbose --cov=. --cov-report=term-missing